# Generated by Django 3.2.5 on 2021-07-29 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(choices=[('Snap for Beauty', 'Salon and makeup services for men and women at home'), ('Snap for Spa', 'Massage therapy for men and women at home'), ('Snap for Grooming', 'Haircut and grooming services for men and kids at home'), ('Snap for Repairs', 'Electricians, plumbers, carpenters, AC and appliance repair'), ('Snap for Cleaning', 'Regular and deep home cleaning solutions'), ('Snap for Painting', 'Professional home painting services'), ('Snap for Event Management', 'Professional weddings & party management services'), ('Snap for fitness', 'Proffessional fitness and yoga services at home')], default='Snap for Beauty', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
